title: Remède Docs
description: The open and free dictionary for everyone.
theme: just-the-docs

url: https://docs.remede.camarm.fr
aux_links:
    Enhance this documentation on Github: https://github.com/labsesoftware/docs.remede.camarm.fr
aux_links_new_tab: false
nav_external_links:
  - title: Public API documentation
    url: https://api-remede.camarm.fr/docs

  - title: Download
    url: https://remede.camarm.fr/download

  - title: Download
    url: https://remede.camarm.fr/download

back_to_top: true
back_to_top_text: "Back to top"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

footer_content: "Copyright &copy; 2023-2024 Labse Software. Template <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT licensed</a>."
