title: Remède documentation
description: The open and free dictionary for everyone.
theme: just-the-docs

url: https://docs.remede.camarm.fr
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
